ACG:
  struct:
    input_size: 192
    f_mid: 512
    layers: 3
  training:
    batch_size: 1
    num_workers: 0
    lr: 1e-8
    weight_decay: 1e-5
    n_iterations: 5
    summary_steps: 2
    autosave_steps: 5

RSA:
  struct:
    cond_len: 192
    level: 2
    c_in: 512
    c_mid: 512
    c_out: 512
    cc_layers: 2
    n_blocks: 1
  training:
    clamp: 1.5
    init_scale: 0.03
    batch_size: 1
    num_workers: 0
    lr: 1e-8
    weight_decay: 1e-5
    decay_by: 0.01
    n_iterations: 5
    summary_steps: 2
    autosave_steps: 5