ACG:
  struct:
    input_size: 192
    f_mid: 512
    layers: 3
  training:
    batch_size: 1
    num_workers: 0
    lr: 1e-8
    weight_decay: 1e-5
    n_iterations: 5
    summary_steps: 2
    autosave_steps: 5

RSA:
  struct:
  training:
    lr: 1e-8
    weight_decay: 1e-5