ACG:
  struct:
    f_in=512
    f_out=512
    layers=10
  training:
    batch_size=1
    num_workers=0
    lr=1e-8
    weight_decay=1e-5
    n_iterations=10
    summary_steps=5

RSA:
  struct:
  training:
    lr=1e-8
    weight_decay=1e-5