ACG:
  struct:
    input_size: 192
    f_mid: 512
    layers: 3
  training:
    batch_size: 1
    num_workers: 0
    lr: 1e-8
    weight_decay: 1e-5
    n_iterations: 5
    summary_steps: 2
    autosave_steps: 5

RSA:
  struct:
    basic:
      cinnb_nums: 2
      key_len: 512
    cinnblock:
      channel: 40
      clamp: 1.5
      cond_len: 192
      cond_trans: 128
    # level: 2
    # c_in: 512
    # c_mid: 512
    # c_out: 512
    # cc_layers: 2
    # n_blocks: 1
  training:
    init_scale: 0.03
    batch_size: 1
    num_workers: 0
    beta1: 0.5
    beta2: 0.999
    eps: 1e-6
    lr: 1e-8
    weight_decay: 1e-5
    decay_by: 0.01
    lambda_1: 1
    lambda_2: 1
    lambda_3: 1
    n_iterations: 5
    summary_steps: 2
    autosave_steps: 5